/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import accesoDatos.ClienteJpaController;
import accesoDatos.RelclientevehiculoJpaController;
import accesoDatos.RelventaservicioJpaController;
import accesoDatos.ServicioJpaController;
import accesoDatos.VehiculoJpaController;
import accesoDatos.VentaJpaController;
import controles.Fachada;
import controles.IFachada;
import dominio.Cliente;
import dominio.Pieza;
import dominio.Relclientevehiculo;
import dominio.Relventapieza;
import dominio.Relventaservicio;
import dominio.Servicio;
import dominio.Vehiculo;
import dominio.Venta;
import java.util.ArrayList;
import java.util.Date;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author l3tal
 */
public class DlgTotalServicio extends javax.swing.JDialog {

    private Venta venta;
    private ArrayList<Servicio> listaServicios;
    private ArrayList<Pieza> listaPieza;
    private IFachada fachada;
    private boolean clienteYaRegistrado;

    public DlgTotalServicio(java.awt.Frame parent, boolean modal, Venta venta, ArrayList<Servicio> listaServicios, boolean clienteYaRegistrado,
            ArrayList<Pieza> listaPieza) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.clienteYaRegistrado = clienteYaRegistrado;
        this.venta = venta;
        this.listaServicios = listaServicios;
        this.listaPieza = listaPieza;
        this.llenarTablaServicios();
        this.llenarTablaPiezas();
        this.totalTF.setText(this.venta.getTotal() + "");
        this.fachada = new Fachada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cambioTF = new javax.swing.JTextField();
        totalTF = new javax.swing.JTextField();
        pagoTF = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaConceptos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPiezas = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Total de la venta");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Total");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("¿Con cuanto va a pagar?");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cambio");

        cambioTF.setEditable(false);

        totalTF.setEditable(false);

        pagoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pagoTFKeyReleased(evt);
            }
        });

        btnPagar.setBackground(new java.awt.Color(0, 204, 0));
        btnPagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tablaConceptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Concepto", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaConceptos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaConceptos);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Servicios");

        tablaPiezas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Concepto", "Monto", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPiezas.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaPiezas);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Piezas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(btnPagar)
                .addGap(52, 52, 52)
                .addComponent(btnCancelar)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cambioTF, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pagoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel9))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel16)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pagoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cambioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        this.agregarVenta();
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void pagoTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagoTFKeyReleased
        String pago = pagoTF.getText();
        boolean isNumeric = pago.chars().allMatch(Character::isDigit);
        if (!isNumeric) {
            JOptionPane.showMessageDialog(this, "Debes singresar un numero",
                    "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            this.pagoTF.setText("");
        } else {
            double pagoInt = Double.parseDouble(pago);
            double totalInt = Double.parseDouble(this.totalTF.getText());
            double cambio = pagoInt - totalInt;
            String cambioStr = String.valueOf(cambio);
            cambioTF.setText(cambioStr);
        }
    }//GEN-LAST:event_pagoTFKeyReleased
    private void agregarVenta() {
        Cliente clienteFinal = this.venta.getIdcliente();
        Vehiculo vehiculoFinal = this.venta.getIdvehiculo();
        Relclientevehiculo relclientevehiculo = new Relclientevehiculo(clienteFinal, vehiculoFinal);

        if (clienteYaRegistrado == false) {
            this.fachada.guardarCliente(clienteFinal);
            this.fachada.guardarVehiculo(vehiculoFinal);
            this.fachada.guardarRelclientevehiculo(relclientevehiculo);
        }

        for (int i = 0; i < this.listaServicios.size(); i++) {
            this.fachada.guardarServicio(this.listaServicios.get(i));
        }

        this.fachada.guardarVenta(venta);
        for (int i = 0; i < this.listaServicios.size(); i++) {
            Servicio servicio = this.listaServicios.get(i);
            Relventaservicio relVentaServicio = new Relventaservicio(servicio, venta);
            this.fachada.guardarRelventaservicio(relVentaServicio);
        }

        for (int i = 0; i < this.listaPieza.size(); i++) {
            Pieza pieza = this.listaPieza.get(i);
            Pieza piezaBD = this.fachada.buscarPorIDPieza(pieza.getIdpieza());
            pieza.setCantidad(piezaBD.getCantidad() - pieza.getCantidad());
            this.fachada.actualizarPieza(pieza);
            Relventapieza relVentaPieza = new Relventapieza(pieza.getCantidad() + "", pieza, venta);
            this.fachada.guardarRelventapieza(relVentaPieza);
        }
        this.dispose();
    }

    private void llenarTablaServicios() {
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tablaConceptos.getModel();
        modeloTabla.setRowCount(0);
        for (Servicio servicio : this.listaServicios) {
            Object[] fila = new Object[2];
            fila[0] = servicio.getConcepto();
            fila[1] = servicio.getCosto();
            modeloTabla.addRow(fila);
        }
        this.centrarDatosTablaProductosBuscados();
    }

    private void llenarTablaPiezas() {
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tablaPiezas.getModel();
        modeloTabla.setRowCount(0);
        for (Pieza pieza : this.listaPieza) {
            Object[] fila = new Object[3];
            fila[0] = pieza.getNombre();
            fila[1] = pieza.getCosto();
            fila[2] = pieza.getCantidad();
            modeloTabla.addRow(fila);
        }
//        this.centrarDatosTablaProductosBuscados();
    }

    private void centrarDatosTablaProductosBuscados() {
        DefaultTableCellRenderer columna = new DefaultTableCellRenderer();
        columna.setHorizontalAlignment(0);
        for (int i = 0; i < this.tablaConceptos.getColumnCount(); i++) {
            this.tablaConceptos.setDefaultRenderer(this.tablaConceptos.getColumnClass(i), columna);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JTextField cambioTF;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField pagoTF;
    private javax.swing.JTable tablaConceptos;
    private javax.swing.JTable tablaPiezas;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
