/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import controles.Fachada;
import controles.IFachada;
import dominio.Pieza;
import dominio.Relventapieza;
import dominio.Relventaservicio;
import dominio.Servicio;
import dominio.Venta;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bryan
 */
public class FrmEditarVenta extends javax.swing.JFrame {

    private ArrayList<Servicio> listaServicios;
    private DlgDetalleServicio dlgDetalleServicio;
    private ArrayList<Pieza> listaPiezas;
    private IFachada fachada;
    private Venta venta;

    /**
     * Creates new form FrmEditarVenta
     */
    public FrmEditarVenta() {
        this.fachada = new Fachada();
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaServicios = new ArrayList<>();
        this.listaPiezas = new ArrayList<>();
        this.dlgDetalleServicio = new DlgDetalleServicio(this, rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistrarVenta = new javax.swing.JButton();
        btnEliminarVenta = new javax.swing.JButton();
        btnEditarVenta = new javax.swing.JButton();
        btnConsultarVenta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clienteNom = new javax.swing.JTextField();
        clienteTel = new javax.swing.JTextField();
        clienteDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notasTF = new javax.swing.JTextPane();
        btnGenerar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        marcaTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        modeloTF = new javax.swing.JTextField();
        idVentaTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fechaVentalbl = new javax.swing.JLabel();
        btnBuscarVenta = new javax.swing.JButton();
        cbVehiculos = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPiezas = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaConceptos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnEliminarServicio = new javax.swing.JButton();
        btnAgregarServicio = new javax.swing.JButton();
        totalVentaTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdmClientes = new javax.swing.JMenu();
        menuAdmVehiculos = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar ventas");
        setResizable(false);

        btnRegistrarVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarVenta.setText("Registrar Venta");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });

        btnEliminarVenta.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminarVenta.setText("Eliminar Venta");
        btnEliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVentaActionPerformed(evt);
            }
        });

        btnEditarVenta.setBackground(new java.awt.Color(51, 51, 240));
        btnEditarVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditarVenta.setText("Editar Venta");
        btnEditarVenta.setEnabled(false);

        btnConsultarVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultarVenta.setText("Consultar Venta");
        btnConsultarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVentaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(220, 220, 220));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Editar Venta");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese el ID de la venta que desea editar");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Informacion del Cliente:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Telefono");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Dirección");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Vehiculos:");

        clienteNom.setEnabled(false);

        clienteTel.setEnabled(false);

        clienteDireccion.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Notas:");

        jScrollPane1.setViewportView(notasTF);

        btnGenerar.setBackground(new java.awt.Color(51, 204, 0));
        btnGenerar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGenerar.setText("Guardar cambios");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Marca");

        marcaTF.setEnabled(false);
        marcaTF.setMinimumSize(new java.awt.Dimension(64, 23));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Nombre");

        nombreTF.setEnabled(false);
        nombreTF.setMinimumSize(new java.awt.Dimension(64, 23));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Modelo");

        modeloTF.setEnabled(false);
        modeloTF.setMinimumSize(new java.awt.Dimension(65, 23));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("ID:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Fecha de la venta:");

        fechaVentalbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnBuscarVenta.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarVenta.setText("Buscar");
        btnBuscarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVentaActionPerformed(evt);
            }
        });

        cbVehiculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vehiculo 1", "Vehiculo 2" }));
        cbVehiculos.setEnabled(false);

        tablaPiezas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Concepto", "Monto", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPiezas.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaPiezas);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Piezas");

        tablaConceptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Concepto", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaConceptos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaConceptos);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Servicios");

        btnEliminarServicio.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminarServicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminarServicio.setText("-");
        btnEliminarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarServicioActionPerformed(evt);
            }
        });

        btnAgregarServicio.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarServicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregarServicio.setText("+");
        btnAgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarServicioActionPerformed(evt);
            }
        });

        totalVentaTF.setText("0.0");
        totalVentaTF.setEnabled(false);
        totalVentaTF.setMinimumSize(new java.awt.Dimension(64, 23));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marcaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modeloTF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idVentaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarVenta)
                        .addGap(226, 226, 226))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel9))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(307, 307, 307)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaVentalbl))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(clienteNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(clienteTel)
                                                .addComponent(clienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalVentaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addGap(69, 69, 69))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idVentaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btnBuscarVenta))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clienteNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clienteTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(marcaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(modeloTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(fechaVentalbl)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalVentaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(btnAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerar)
                        .addGap(32, 32, 32))))
        );

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Salir");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRegistrarVenta)
                                    .addComponent(btnEditarVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnConsultarVenta)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnEliminarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnEditarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnConsultarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(37, 37, 37))
        );

        menuAdmClientes.setText("Administrar Clientes");
        menuAdmClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAdmClientesMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAdmClientes);

        menuAdmVehiculos.setText("Administrar Vehiculos");
        menuAdmVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAdmVehiculosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAdmVehiculos);

        jMenu3.setText("Administrar Ventas");
        jMenu3.setEnabled(false);
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        this.guardarCambios();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void guardarCambios() {
        //actualizar nuevos servicios con ventas
        List<Relventaservicio> listVentaServicio = this.fachada.buscarTodasRelventaservicio();
        for (int i = 0; i < listVentaServicio.size(); i++) {
            int idVenta = this.venta.getIdventa();
            int idListaVenta = listVentaServicio.get(i).getIdventa().getIdventa();
            if (idVenta == idListaVenta) {
                this.fachada.eliminarRelventaservicio(listVentaServicio.get(i).getIdrelVentaServicio());
                this.fachada.eliminarServicio(listVentaServicio.get(i).getIdservicio().getIdservicio());
            }
        }

        for (int i = 0; i < this.listaServicios.size(); i++) {
            Servicio servicio = new Servicio(this.listaServicios.get(i).getFecha(),
                    this.listaServicios.get(i).getCosto(),
                    this.listaServicios.get(i).getConcepto());
            this.fachada.guardarServicio(servicio);
            Relventaservicio relVentaServicio = new Relventaservicio(servicio, this.venta);
            this.fachada.guardarRelventaservicio(relVentaServicio);
        }
/////////////////////////////////////////////////////////////////////
//actualizar nuevas piezas con ventas
        List<Relventapieza> listVentaPieza = this.fachada.buscarTodasRelventapieza();
//
        for (int i = 0; i < listVentaPieza.size(); i++) {
            if (this.venta.getIdventa() == listVentaPieza.get(i).getIdventa().getIdventa()) {
                this.fachada.eliminarRelventapieza(listVentaPieza.get(i).getIdrelventapieza());
                //no se elimina la pieza, se suma la cantidad que se desocupo al quitarlo de la lista
            }
        }
//        //sumar las piezas eliminadas
//        for (int i = 0; i < this.listaPiezas.size(); i++) {
//            Pieza pieza = this.listaPiezas.get(i);
//            Pieza piezaBD = this.fachada.buscarPorIDPieza(pieza.getIdpieza());
//            int piezaBDCantidad = piezaBD.getCantidad();
//            int piezaCantidad = pieza.getCantidad();
//            piezaBD.setCantidad(piezaBDCantidad + piezaCantidad);
//            this.fachada.actualizarPieza(piezaBD);
//        }
        //restar las piezas usadas
        for (int i = 0; i < this.listaPiezas.size(); i++) {
            Pieza pieza = new Pieza(this.listaPiezas.get(i).getNombre(),
                    this.listaPiezas.get(i).getCosto(),
                    this.listaPiezas.get(i).getCantidad());
            Pieza piezaBD = this.fachada.buscarPorIDPieza(this.listaPiezas.get(i).getIdpieza());
            int piezaBDCantidad = piezaBD.getCantidad();
            int piezaCantidad = pieza.getCantidad();
            piezaBD.setCantidad(piezaBDCantidad - piezaCantidad);
            this.fachada.actualizarPieza(piezaBD);
            Relventapieza relVentaPieza = new Relventapieza(piezaCantidad + "", pieza.getCosto(), piezaBD, this.venta);
            this.fachada.guardarRelventapieza(relVentaPieza);
        }
/////////////////////////////////////////////////////////////
        String notas = this.notasTF.getText();
        Double total = Double.parseDouble(this.totalVentaTF.getText());
        if (!this.venta.getNotas().equals(notas) || this.venta.getTotal() != total) {
            this.venta.setNotas(notas);
            this.venta.setTotal(total);
            this.fachada.actualizarVenta(venta);
        }
    }

    private Double obtenerTotalVenta() {
        Double total = 0.0;
        for (Servicio listaServicio : this.listaServicios) {
            total += listaServicio.getCosto();
        }
        for (Pieza pieza : this.listaPiezas) {
            total += pieza.getCosto();
        }
        return total;
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.salirAdministrarVentas();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVentaActionPerformed
        this.buscarVenta();
    }//GEN-LAST:event_btnBuscarVentaActionPerformed

    private void buscarVenta() {
        if (this.idVentaTF.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar un ID a buscar.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            int idVenta = Integer.parseInt(this.idVentaTF.getText());
            this.buscarVenta(idVenta);
        }
    }

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        this.mostrarFrmRegistrarVenta();
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void btnEliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVentaActionPerformed
        this.mostrarFrmEliminarVenta();
    }//GEN-LAST:event_btnEliminarVentaActionPerformed

    private void btnConsultarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVentaActionPerformed
        this.mostrarFrmConsultarVentas();
    }//GEN-LAST:event_btnConsultarVentaActionPerformed

    private void btnEliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarServicioActionPerformed
        this.eliminarServicioPieza();
    }//GEN-LAST:event_btnEliminarServicioActionPerformed

    private void eliminarServicioPieza() {
        int renglonConceptos = this.tablaConceptos.getSelectedRow();
        int renglonPiezas = this.tablaPiezas.getSelectedRow();

        if (renglonConceptos == -1 && renglonPiezas == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un Servicio o Pieza a eliminar",
                    "Advertencia", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (renglonConceptos != -1) {
                this.listaServicios.remove(renglonConceptos);
                this.llenarTablaServicios();
                this.totalVentaTF.setText(this.obtenerTotalVenta() + "");
            }
            if (renglonPiezas != -1) {
                this.listaPiezas.remove(renglonPiezas);
                this.llenarTablaPiezas();
                this.totalVentaTF.setText(this.obtenerTotalVenta() + "");
            }
        }
    }

    private void btnAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServicioActionPerformed
        this.agregarServicioVenta();
    }//GEN-LAST:event_btnAgregarServicioActionPerformed

    private void menuAdmClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAdmClientesMouseClicked
        FrmRegistrarCliente frmRegistrarCliente = new FrmRegistrarCliente();
        frmRegistrarCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuAdmClientesMouseClicked

    private void menuAdmVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAdmVehiculosMouseClicked
        FrmRegistrarVehiculo frmAdmVehiculos = new FrmRegistrarVehiculo();
        frmAdmVehiculos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuAdmVehiculosMouseClicked

    private void agregarServicioVenta() {
        this.dlgDetalleServicio.setVisible(true);
        Servicio servicio = this.dlgDetalleServicio.getServicio();
        Pieza pieza = this.dlgDetalleServicio.getPieza();
        if (servicio != null) {
            this.listaServicios.add(servicio);
            this.llenarTablaServicios();
            this.totalVentaTF.setText(this.obtenerTotalVenta() + "");
        }
        if (pieza != null) {
            this.listaPiezas.add(pieza);
            this.llenarTablaPiezas();
            this.totalVentaTF.setText(this.obtenerTotalVenta() + "");
        }
        this.dlgDetalleServicio.setServicio(null);
        this.dlgDetalleServicio.setPieza(null);
    }

    private void mostrarFrmRegistrarVenta() {
        FrmRegistrarVenta frmRegistrarVenta = new FrmRegistrarVenta();
        frmRegistrarVenta.setVisible(true);
        this.dispose();
    }

    private void mostrarFrmConsultarVentas() {
        FrmConsultarVentas frmMostrarVentas = new FrmConsultarVentas();
        frmMostrarVentas.setVisible(true);
        this.dispose();
    }

    private void mostrarFrmEliminarVenta() {
        FrmEliminarVenta frmEliminarVenta = new FrmEliminarVenta();
        frmEliminarVenta.setVisible(true);
        this.dispose();
    }

    private void salirAdministrarVentas() {
        FrmInicioSesion frmInicioSesion = new FrmInicioSesion();
        frmInicioSesion.setVisible(true);
        this.dispose();
    }

    private void buscarVenta(int idVenta) {
        this.venta = this.fachada.buscarPorIDVenta(idVenta);
        this.listaPiezas.clear();
        this.listaServicios.clear();
        if (this.venta != null) {
            this.llenarDatosVenta(this.venta);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Venta no encontrada.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    private void llenarDatosVenta(Venta venta) {
        this.fechaVentalbl.setText(new SimpleDateFormat("dd-MM-yyyy").format(venta.getFecha()));
        this.clienteNom.setText(venta.getIdcliente().getNombre());
        this.clienteTel.setText(venta.getIdcliente().getTelefono());
        this.clienteDireccion.setText(venta.getIdcliente().getDireccion());

        this.marcaTF.setText(venta.getIdvehiculo().getMarca());
        this.nombreTF.setText(venta.getIdvehiculo().getNombre());
        this.modeloTF.setText(venta.getIdvehiculo().getModelo());

        this.notasTF.setText(venta.getNotas());

        List<Relventaservicio> relVentaServicio = this.fachada.buscarTodasRelventaservicio();
        List<Relventaservicio> listaVentaServicios = new ArrayList<>();

        List<Relventapieza> relVentaPieza = this.fachada.buscarTodasRelventapieza();
        List<Relventapieza> listaVentaPiezas = new ArrayList<>();

        for (int i = 0; i < relVentaServicio.size(); i++) {
            if (relVentaServicio.get(i).getIdventa().getIdventa() == venta.getIdventa()) {
                listaVentaServicios.add(relVentaServicio.get(i));
            }
        }
        for (Relventaservicio listaVentaServicio : listaVentaServicios) {
            this.listaServicios.add(listaVentaServicio.getIdservicio());
        }

        for (int i = 0; i < relVentaPieza.size(); i++) {
            if (relVentaPieza.get(i).getIdventa().getIdventa() == venta.getIdventa()) {
                listaVentaPiezas.add(relVentaPieza.get(i));
            }
        }
        for (Relventapieza listaVentaPieza : listaVentaPiezas) {
            int cantidadNueva = Integer.parseInt(listaVentaPieza.getCantidad());
            double costoNuevo = listaVentaPieza.getCosto();
            listaVentaPieza.getIdpieza().setCantidad(cantidadNueva);
            listaVentaPieza.getIdpieza().setCosto(costoNuevo);
            this.listaPiezas.add(listaVentaPieza.getIdpieza());
        }

        this.llenarTablaServicios();
        this.llenarTablaPiezas();
        this.totalVentaTF.setText(venta.getTotal() + "");
    }

    private void llenarTablaServicios() {
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tablaConceptos.getModel();
        modeloTabla.setRowCount(0);
        for (Servicio servicio : this.listaServicios) {
            Object[] fila = new Object[2];
            fila[0] = servicio.getConcepto();
            fila[1] = servicio.getCosto();
            modeloTabla.addRow(fila);
        }
        this.centrarDatosTablaServicios();
    }

    private void llenarTablaPiezas() {
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tablaPiezas.getModel();
        modeloTabla.setRowCount(0);
        for (Pieza pieza : this.listaPiezas) {
            Object[] fila = new Object[3];
            fila[0] = pieza.getNombre();
            fila[1] = pieza.getCosto();
            fila[2] = pieza.getCantidad();
            modeloTabla.addRow(fila);
        }
        this.centrarDatosTablaPiezas();
    }

    private void centrarDatosTablaServicios() {
        DefaultTableCellRenderer columna = new DefaultTableCellRenderer();
        columna.setHorizontalAlignment(0);
        for (int i = 0; i < this.tablaConceptos.getColumnCount(); i++) {
            this.tablaConceptos.setDefaultRenderer(this.tablaConceptos.getColumnClass(i), columna);
        }
    }

    private void centrarDatosTablaPiezas() {
        DefaultTableCellRenderer columna = new DefaultTableCellRenderer();
        columna.setHorizontalAlignment(0);
        for (int i = 0; i < this.tablaPiezas.getColumnCount(); i++) {
            this.tablaPiezas.setDefaultRenderer(this.tablaPiezas.getColumnClass(i), columna);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarServicio;
    private javax.swing.JButton btnBuscarVenta;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultarVenta;
    private javax.swing.JButton btnEditarVenta;
    private javax.swing.JButton btnEliminarServicio;
    private javax.swing.JButton btnEliminarVenta;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JComboBox<String> cbVehiculos;
    private javax.swing.JTextField clienteDireccion;
    private javax.swing.JTextField clienteNom;
    private javax.swing.JTextField clienteTel;
    private javax.swing.JLabel fechaVentalbl;
    private javax.swing.JTextField idVentaTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField marcaTF;
    private javax.swing.JMenu menuAdmClientes;
    private javax.swing.JMenu menuAdmVehiculos;
    private javax.swing.JTextField modeloTF;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JTextPane notasTF;
    private javax.swing.JTable tablaConceptos;
    private javax.swing.JTable tablaPiezas;
    private javax.swing.JTextField totalVentaTF;
    // End of variables declaration//GEN-END:variables
}
